### ISSUE TITLE
Разработать JSON SUQL как расширение синтаксиса SuQL

### ISSUE THREAD

**Issue by sagittaracc** [sagittaracc/suql#357]
JSON SUQL 
```json
    {
        "app\\models\\Users": {
            "id": "uid",
            "name": {
                "order": "asc",
                "as": "uname"
            },
            "app\\models\\Groups": {
                "id": "gid",
                "name": "gname" 
            }
        }
    }
```

**Comment by sagittaracc** [comment]
Добавить новый SuQLJson синтакс. Написать SuQLJsonParser

**Comment by sagittaracc** [comment]
Разработать SuQLDataSet как расширение синтаксиса SuQL

**Comment by sagittaracc** [comment]
PermissionControl должен выбрасывать исключение если доступ не разрешен

**Comment by sagittaracc** [comment]
Лучше перейти на Yaml

**Comment by sagittaracc** [comment]
```yaml
app\models\Users:
    id: uid,
    name:
        order: asc,
        as: uname
    app\models\Groups:
        id: gid,
        name: gname
```
